### ISSUE TITLE
more-itertools required version is not supported

### ISSUE THREAD

**Issue by apassiou** [sumpfork/dominiontabs#279]
Requirements.txt points to 7.2.0 which is the latest version, but Python2.7 hasnt been supported since 5.0 so installation of requirements.txt fails as 7.2.0 cant be found.

And this project is not Python 3.0 compliant as setup.py uses Python 2.7 syntax.

**Comment by sumpfork** [comment]
We've supported python 3 for a long time, and CI runs python 3, which passes (see e.g. https://travis-ci.org/sumpfork/dominiontabs/builds/600565172). I recently stopped supporting python 2.x.

**Comment by apassiou** [comment]
Strangely I get print statement syntax errors (the code seems to be python2 syntax for print).

```
$ dominion_dividers
Traceback (most recent call last):
  File "C:\Users\Duxa\AppData\Local\Programs\Python\Python38-32\Scripts\dominion_dividers-script.py", line 11, in <module>
    load_entry_point('domdiv', 'console_scripts', 'dominion_dividers')()
  File "C:\Users\Duxa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\Duxa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Users\Duxa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Users\Duxa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\Duxa\AppData\Local\Programs\Python\Python38-32\lib\site-packages\domdiv\main.py", line 500
    print 'Using custom paper size, %.2fcm x %.2fcm' % (
          ^
SyntaxError: invalid syntax
```

**Comment by sumpfork** [comment]
There's no such line on current master: https://github.com/sumpfork/dominiontabs/blob/master/src/domdiv/main.py#L949 and https://github.com/sumpfork/dominiontabs/blob/master/src/domdiv/main.py#L985 are the two candidates.

**Comment by apassiou** [comment]
Thats so strange, I tried checking out with git and manually downloading the master branch... still same error... 

I was getting zlib dependency issues on Windows, and its a nightmare to install on Windows, so I even tried Debian. Same problem.

**Comment by sumpfork** [comment]
I don't believe this is a valid issue as titled as far as I can tell from your notes. If you're still having trouble with a windows install, please make a new issue for that.
